In [ ]:
# Install libraries on the uv venv 
!uv add pandas
!uv add numpy

Resolved 6 packages in 709ms
   Building ecobicis-proyecto @ file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto
      Built ecobicis-proyecto @ file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto
Downloading pandas (10.2MiB)
 Downloaded pandas
Prepared 2 packages in 2.22s
Uninstalled 1 package in 3ms
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 3.37s
 ~ ecobicis-proyecto==0.1.0 (from file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto)
 + numpy==2.5.4
 + pandas==3.1.0
Resolved 6 packages in 34ms
   Building ecobicis-proyecto @ file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto
      Built ecobicis-proyecto @ file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto
Prepared 1 package in 51ms
Uninstalled 1 package in 2ms
Installed 1 package in 18ms
 ~ ecobicis-proyecto==0.1.0 (from file:///C:/Users/Nico/Documents/GitHub/EcoBicis_proyecto)

In [3]:
import pandas as pd
import numpy as np

In [35]:
def fix_twiced_numbered_station(station):
	try: return int(station)
	except ValueError: 
		return int(station.split("-")[0] ) # "001-002" -> [001,002] -> 001

## DataFrame de los viajes (1498933 viajes, septiembre 2026)

In [ ]:
viajes_ruta = r"data\viajes_ecobici.csv"
viajes_df = pd.read_csv(viajes_ruta)

viajes_df.head()

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo
0,M,30.0,6583322,028,31/08/2026,23:54:59,258,01/09/2026,00:00:03
1,F,33.0,4139655,030,31/08/2026,23:24:43,530,01/09/2026,00:00:04
2,O,32.0,6378079,139,31/08/2026,23:46:59,559,01/09/2026,00:00:35
3,M,35.0,6074272,365,31/08/2026,23:52:10,312,01/09/2026,00:00:44
4,M,30.0,4162376,412,31/08/2026,23:51:45,337,01/09/2026,00:00:55

In [63]:
viajes = viajes_df.copy()


# ====== Formatos ======
# Horario de retiro
viajes["Fecha_Hora_Retiro"] = pd.to_datetime(
    viajes["Fecha_Retiro"] + " " + viajes["Hora_Retiro"], 
    format="%d/%m/%Y %H:%M:%S"  )


# Horario de arribo
viajes["Fecha_Hora_Arribo"] = pd.to_datetime(
    viajes["Fecha_Arribo"] + " " + viajes["Hora_Arribo"], 
    format="%d/%m/%Y %H:%M:%S"  )


# EStaciones
viajes["Ciclo_EstacionArribo"] = viajes["Ciclo_EstacionArribo"].apply(fix_twiced_numbered_station)
viajes["Ciclo_Estacion_Retiro"] = pd.to_numeric(viajes["Ciclo_Estacion_Retiro"]).apply(fix_twiced_numbered_station)

ValueError: Unable to parse string '235-236' at position 5

In [59]:
viajes

,Genero_Usuario,Edad_Usuario,Bici,Ciclo_Estacion_Retiro,Fecha_Retiro,Hora_Retiro,Ciclo_EstacionArribo,Fecha_Arribo,Hora_Arribo,Fecha_Hora_Retiro,Fecha_Hora_Arribo
0,M,30.0,6583322,028,2026-08-31,23:54:59,258,2026-09-01,00:00:03,2026-08-31 23:54:59,2026-09-01 00:00:03
1,F,33.0,4139655,030,2026-08-31,23:24:43,530,2026-09-01,00:00:04,2026-08-31 23:24:43,2026-09-01 00:00:04
2,O,32.0,6378079,139,2026-08-31,23:46:59,559,2026-09-01,00:00:35,2026-08-31 23:46:59,2026-09-01 00:00:35
3,M,35.0,6074272,365,2026-08-31,23:52:10,312,2026-09-01,00:00:44,2026-08-31 23:52:10,2026-09-01 00:00:44
4,M,30.0,4162376,412,2026-08-31,23:51:45,337,2026-09-01,00:00:55,2026-08-31 23:51:45,2026-09-01 00:00:55
...,...,...,...,...,...,...,...,...,...,...,...
1498929,M,45.0,5402276,513,2026-09-30,23:50:37,519,2026-09-30,23:59:32,2026-09-30 23:50:37,2026-09-30 23:59:32
1498930,M,37.0,4451399,041,2026-09-30,23:48:44,183,2026-09-30,23:59:32,2026-09-30 23:48:44,2026-09-30 23:59:32
1498931,M,44.0,6252977,693,2026-09-30,23:54:10,440,2026-09-30,23:59:39,2026-09-30 23:54:10,2026-09-30 23:59:39
1498932,M,33.0,3056892,057,2026-09-30,23:54:23,028,2026-09-30,23:59:54,2026-09-30 23:54:23,2026-09-30 23:59:54
1498933,M,34.0,7056013,135,2026-09-30,23:33:48,541,2026-09-30,23:59:57,2026-09-30 23:33:48,2026-09-30 23:59:57

In [60]:
viajes.info()

<class 'pandas.DataFrame'>
RangeIndex: 1498934 entries, 0 to 1498933
Data columns (total 11 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Genero_Usuario         1498934 non-null  str
 1   Edad_Usuario           1498905 non-null  float64
 2   Bici                   1498934 non-null  int64
 3   Ciclo_Estacion_Retiro  1498934 non-null  str
 4   Fecha_Retiro           1498934 non-null  datetime64[us]
 5   Hora_Retiro            1498934 non-null  object
 6   Ciclo_EstacionArribo   1498934 non-null  str
 7   Fecha_Arribo           1498934 non-null  datetime64[us]
 8   Hora_Arribo            1498934 non-null  object
 9   Fecha_Hora_Retiro      1498934 non-null  datetime64[us]
 10  Fecha_Hora_Arribo      1498934 non-null  datetime64[us]
dtypes: datetime64[us](4), float64(1), int64(1), object(2), str(3)
memory usage: 125.8+ MB

## DataFrame de las estaciones

In [40]:
estaciones_ruta = r"data\estaciones_ecobici.csv"
stations_df = pd.read_csv(estaciones_ruta)
stations_df.head()

,sistema,num_cicloe,calle_prin,calle_secu,colonia,alcaldia,latitud,longitud,sitio_de_e,estatus
0,Ecobici,423,Moras,Eje 8 Sur Jose Maria Rico,Acacias,Benito Juarez,19.367816,-99.175269,Arroyo,Instalada
1,Ecobici,437,Moras,Comunal,Acacias,Benito Juarez,19.364916,-99.175985,Arroyo,Instalada
2,Ecobici,438,Adolfo Prieto,Jose Maria Olloqui,Acacias,Benito Juarez,19.364730,-99.174447,Arroyo,Instalada
3,Ecobici,439,Amores,Avenida Coyoacan,Acacias,Benito Juarez,19.362037,-99.172683,Arroyo,Instalada
4,Ecobici,440,Martin Mendalde,M. Lopez Cotilla,Acacias,Benito Juarez,19.361699,-99.171387,Arroyo,Instalada

In [44]:
stations = stations_df.copy()

try: stations = stations.drop(columns = ["sistema"])
except KeyError: print("sistema ya fue eliminado o no se encontró \n")

# Cambiar num_cicloe a numerico 
stations["num_cicloe"] = stations["num_cicloe"].apply(fix_twiced_numbered_station)

In [45]:
stations

,num_cicloe,calle_prin,calle_secu,colonia,alcaldia,latitud,longitud,sitio_de_e,estatus
0,423,Moras,Eje 8 Sur Jose Maria Rico,Acacias,Benito Juarez,19.367816,-99.175269,Arroyo,Instalada
1,437,Moras,Comunal,Acacias,Benito Juarez,19.364916,-99.175985,Arroyo,Instalada
2,438,Adolfo Prieto,Jose Maria Olloqui,Acacias,Benito Juarez,19.364730,-99.174447,Arroyo,Instalada
3,439,Amores,Avenida Coyoacan,Acacias,Benito Juarez,19.362037,-99.172683,Arroyo,Instalada
4,440,Martin Mendalde,M. Lopez Cotilla,Acacias,Benito Juarez,19.361699,-99.171387,Arroyo,Instalada
...,...,...,...,...,...,...,...,...,...
672,697,Francisco Sosa,Tres Cruces,Villa Coyoacan,Coyoacan,19.349277,-99.164921,Arroyo,Instalada
673,698,Cda. Alberto Zamora,Av. Miguel Angel de Quevedo,Villa Coyoacan,Coyoacan,19.344855,-99.163575,Arroyo,Instalada
674,699,San Gregorio,Felipe Carrillo Puerto,Villa Coyoacan,Coyoacan,19.346895,-99.163868,Arroyo,Instalada
675,441,Puente Xoco,Real de Mayorazgo,Xoco,Benito Juarez,19.361213,-99.167520,Arroyo,Instalada
676,442,Real de Mayorazgo,Avenida Mexico-Coyoacan,Xoco,Benito Juarez,19.359863,-99.165065,Arroyo,Instalada

In [46]:
stations.info()

<class 'pandas.DataFrame'>
RangeIndex: 677 entries, 0 to 676
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   num_cicloe  677 non-null    int64
 1   calle_prin  677 non-null    str
 2   calle_secu  677 non-null    str
 3   colonia     677 non-null    str
 4   alcaldia    677 non-null    str
 5   latitud     677 non-null    float64
 6   longitud    677 non-null    float64
 7   sitio_de_e  677 non-null    str
 8   estatus     677 non-null    str
dtypes: float64(2), int64(1), str(6)
memory usage: 47.7 KB